[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nsgd = "coUnmi3oBUtwtd9fjeAvSsJssXh5A5xyPbhpewyzRVF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./tests/fixtures/keys/program-owner.json"

[scripts]
test = "../node_modules/.bin/vitest --dir ./"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = "../solana-ledger"
rpc_port = 8899
